services:
  mongo:
    image: mongo:6
    container_name: task_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./task-manager-backend
      dockerfile: Dockerfile
    container_name: task_backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/taskdb
      JWT_SECRET: supersecretjwt
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./task-manager-frontend
      dockerfile: Dockerfile
    container_name: task_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data: