version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/taskdb
      JWT_SECRET: super_secret_change_me
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "5000:5000"

volumes:
  mongo_data:
